influxdb:
  image: influxdb:latest
  container_name: influxdb
  volumes:
    - /Users/oliver/Data/influxdb:/var/lib/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  volumes:
    - /Users/oliver/Data/grafana:/var/lib/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
